export const TOGGLE_ALL = 'TOGGLE_ALL';
export const UNSET_ALL = 'UNSET_ALL';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const SET_SORT_BY = 'SET_SORT_BY';

export const FETCH_SEARCH_ID_REQUEST = 'FETCH_SEARCH_ID_REQUEST';
export const FETCH_SEARCH_ID_SUCCESS = 'FETCH_SEARCH_ID_SUCCESS';
export const FETCH_SEARCH_ID_ERROR = 'FETCH_SEARCH_ID_ERROR';

export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST';
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_ERROR = 'FETCH_TICKETS_SUCCESS';

export const LOAD_MORE_TICKETS = 'LOAD_MORE_TICKETS';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SORT_TICKETS = 'SORT_TICKETS';
